<div class="row">                
    <div class="col-md-6">
        All rights reserved. Copyright &copy; <?php echo $this->layout()->copyright_year; ?>
        <a href="<?php echo $this->url('home') ?>"> <?php echo $this->layout()->organization; ?></a>
    </div>
    <div class="cold-md-6">
        <span class="pull-right">
            A proud partner of <a href="http://www.codingmatters.io" target="_blank">Coding Matters, Inc.</a>                            
        </span>
    </div>
</div>