<div class="row">
    <div class="col-md-4">
        <h1 class="logo logo--light"><span class="l"><?php echo $this->layout()->application_name; ?></h1>
        <p class="description">
            <?php echo $this->layout()->description; ?>
        </p>
        <ul class="social-links">
            <li class="social-link">
                <i class="fa fa-facebook-official"></i>
            </li>
            <li class="social-link">
                <i class="fa fa-twitter-square"></i>              
            </li>

            <li class="social-link">
                <i class="fa fa-linkedin-square"></i>
            </li>
        </ul>
    </div>
    <div class="col-md-8">
        <div class="col-md-3">
            <h5 class="heading">Menu#1</h5>
            <ul class="zeroed">
                <li><a href="#">Option#1</a></li>
                <li><a href="#">Option#2</a></li>
                <li><a href="#">Option#3</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h5 class="heading">Menu#2</h5>
            <ul class="zeroed">
                <li><a href="#">Option#1</a></li>
                <li><a href="#">Option#2</a></li>
                <li><a href="#">Option#3</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h5 class="heading">Menu#3</h5>
            <ul class="zeroed">
                <li><a href="#">Option#1</a></li>
                <li><a href="#">Option#2</a></li>
                <li><a href="#">Option#3</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h5 class="heading">Menu#4</h5>
            <ul class="zeroed">
                <li><a href="#">Option#1</a></li>
                <li><a href="#">Option#2</a></li>
                <li><a href="#">Option#3</a></li>
            </ul>
        </div>
    </div>
</div>